language: php
php:
  - '7.2'

services:
  - mysql

install:
  - composer self-update
  - composer install --no-interaction
  - pip install --user awscli

before_script:
  - mysql -e 'create database thyart_testing;'
  - cp .env.travis .env.testing
  - php artisan key:generate --env=testing
  - php artisan migrate --env=testing
  - php artisan passport:keys --env=testing

script:
  - ./vendor/bin/phpunit

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
