language: php
php:
- '7.2'
services:
- mysql
install:
- pip install --user awscli
- composer self-update
- composer install --no-interaction
before_script:
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- mysql -e 'create database thyart_testing;'
- cp .env.travis .env.testing
- php artisan key:generate --env=testing
- php artisan migrate --env=testing
- php artisan passport:keys --env=testing
script:
- "./vendor/bin/phpunit"
after_success:
  - chmod +x .travis/getenv.sh
  - ./.travis/getenv.sh
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - secure: cjm+7ZrWSg67H11kSP1wQuRQD6YrtIavY3p/5yIYy8hVYNL0vkwMkpT2934s3VglJtBOxR1m2+5pseHJQGB0mACjnRX2kJnIpr3gJ+qhBN8D9Tc4Q1PNLUfX09Bc97jhgmHIU9OjMlAYCMCzOEFHlp0TBOHe+EL/cIUVH1bTaxuFC7HeqxTtqFwAU/Llk2yV/oJe081huEcvv+MfNjIxrYg9yBKsI1MkdtqfvwXAI0f9X6cFs/YeegABc9YPRqjVF8tAulPkfI6EvKzm63dIGLPGeMiuTcS/2ncAtpR/an0xnza1gq0PmI+E61+v1ZCYKpm0Gg1aCgGHyO4KYEdlJVgdGAukDw4EMo6DxE2fKz5EXdxbwIDU2ozzYbuS1R0sYYwSf1Ys3UUkyqxDpQrpItbp6wFRnGYZU2ur2NZ9MAtLJeMeY9FNndQAoEVFw/063+2ZQyEzdGeCeVh1+wZLIq1iqF5a0luxn+467DrO/uYvTZpWfCRV+rpx1hVaBpHixMisFNg5geaOWWk7GZLugapJGGXXaqoQqWCY5cV52hd03aFQ6DEE8y1yAOsUQ5+7OfZooWdMGO+E55usRKUnIkI1Ugj4BG/fgpXdJWtGgZLRECVSC17au/B7oxxSkHTIelmVztjKl1bWfWwep0yNo4MA9GS41Wqv6MkaKVVklK8=
  - secure: NfgxIcknmhLuWE8Rpzjt1zbsybB/Fuj/VrVcwhvlXxct3y4GpKuG834vhEwer8yM0xv+TGeAVhe4f2vOhQW8vSB5dj2fYd/0ZBCSVLnKRaVgLvPYJ6ozwQgaPv+XmGeoS4387BrI1g8/TyWeDUTSpUBrH9GsbZsRpW3+RLCJYgGlts1LuuqNGHZ3yMfYqmLx5ibNPDmnuHphsIYZui0a713k/kqADMvYugFByW/K0V7dg1NAsDqS3W0cOcDuJ43hoG/dTP15KSh7Flr/p4mDHEE0VGpgP7XZvxNMHGql3zAosaCKU1Yv8Iu+O2KHRYX43sdqB6vJwgBz4b4RPrCauAlpCbHMUM+0ZOUINENs+gjuVTo9yBto3587/otcTTkWVeNE5m5vuL4R4MNDK8hFuzO4znkqLBenOZlPeOTYKFiRaX7GhxmXIMIASVvi5UqnP6GSLJTn9z/ukSWxaS7QYK/fcQ+Wq+yRWW/fHA3NNXbhpcZ9sE4UA0xX4eTT/QpEMbRLV7U+2IJKQvqXlKkBI4q+h7pmi3Mex/K4VdSfWyLjvzaWUbXYBV/nHNBl3CBGaDHmNqIuuq+7rkptg2lc0LWtPe5fqzT13hZFZ8PNpf5fYXPWdPrOzTnjBdl5utqYsVTcDlLbya/YGF6Ng+aszKV9Q73KBIlrAf0bA1t4BNU=
