version: 0.2

phases:
  install:
    commands:
      - service mysql start
      - mysql -u root -e "CREATE DATABASE thyart_codebuild;"
  pre_build:
    commands:
       - cp .env.codebuild .env
  build:
    commands:
      - composer install --no-interaction --prefer-dist
      - php artisan key:generate
      - php artisan migrate:refresh
      - php artisan passport:keys
      - ./vendor/bin/phpunit
  post_build:
    commands:
      - rm .env
      - aws configure set aws_access_key_id $ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
      - aws configure set default.region eu-west-1
      - aws s3 cp s3://thyart-environment-files/dev/dev-environment .env
      - aws s3 cp s3://thyart-environment-files/dev/oauth-private.key storage/oauth-private.key
      - aws s3 cp s3://thyart-environment-files/dev/oauth-public.key storage/oauth-public.key
      - service mysql stop

artifacts:
  files:
    - .env
    - artisan
    - composer.json
    - composer.lock
    - phpunit.xml
    - server.php
    - .ebextensions/**/*
    - app/**/*
    - bootstrap/**/*
    - config/**/*
    - database/**/*
    - public/**/*
    - resources/**/*
    - routes/**/*
    - storage/**/*
    - tests/**/*
    - vendor/**/*